import type { CourseSearchItem } from "./types";

export const mockSearchResults: CourseSearchItem[] = [
  {
    course_id: "1",
    course_title: "Beginner's Yoga Flow",
    sport_name: "Yoga",
    coach_name: "Sarah Chen",
    coach_nickname: "Coach Sarah",
    city: "Atlanta",
    certificates: ["RYT-200", "ACE"],
    price_per_session: 45,
    price_per_hour: 60,
    styles: ["Vinyasa", "Hatha"],
    comm_styles: ["Encouraging"],
    pace_intensities: ["Moderate"],
    prefer_students: ["Beginners"],
    match_score: 95,
  },
  {
    course_id: "2",
    sport_name: "Boxing",
    coach_name: "Mike Johnson",
    city: "Buckhead",
    certificates: ["NASM-CPT"],
    price_per_hour: 75,
    styles: ["Traditional", "Cardio"],
    pace_intensities: ["High"],
    prefer_students: ["Intermediate"],
    match_score: 85,
  },
  {
    course_id: "3",
    course_title: "Power HIIT & Strength",
    sport_name: "HIIT",
    coach_name: "Alex Thompson",
    coach_nickname: "Coach Alex",
    city: "Midtown",
    certificates: ["NSCA-CSCS", "CrossFit L2"],
    price_per_session: 55,
    styles: ["Circuit", "Strength"],
    comm_styles: ["Motivational", "Direct"],
    pace_intensities: ["High"],
    match_score: 78,
  },
];
