services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway
      - chat-service
      - user-service
      - course-service

  api-gateway:
    build:
      context: ./backend/apigateway
    expose:
      - "8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
    depends_on:
      - user-service
      - course-service

  chat-service:
    build:
      context: ./backend/chatservice
    expose:
      - "4000"
    env_file:
      - ./backend/chatservice/.env

  user-service:
    build:
      context: ./backend/userservice
    expose:
      - "8081"

  course-service:
    build:
      context: ./backend/courseservice
    expose:
      - "8082"