#!/bin/bash

# 测试教练dashboard时间表功能
echo "🧪 测试教练dashboard时间表功能"
echo "=============================="

echo "📋 功能描述："
echo "在教练dashboard的coach center页面添加时间表"
echo "显示有学生的课程（session和availability）"
echo "以固定时段session的形式显示"
echo ""

echo "🔧 实现内容："
echo "1. ✅ 前端API - getCoachBookedSessions()"
echo "2. ✅ 后端API - GET /bookings/coach/{coachId}/booked-sessions"
echo "3. ✅ 数据库查询 - 联合查询session和availability预约"
echo "4. ✅ 前端UI - CoachCenterPage添加时间表组件"
echo "5. ✅ 时间表组件 - 复用UserScheduleWeekView"
echo ""

echo "📊 数据流程："
echo "1. 教练登录后获取coachId"
echo "2. 调用API获取有学生的课程"
echo "3. SQL查询："
echo "   - Session预约：显示课程名称、学生数量"
echo "   - Availability预约：显示为固定时段"
echo "4. 前端转换为日历事件格式"
echo "5. 在时间表中显示"
echo ""

echo "🎯 预期结果："
echo "- 项目卡片正常显示"
echo "- 时间表显示有学生的课程"
echo "- Session显示课程名称和学生数量"
echo "- Availability显示为固定时段"
echo "- 可以切换周视图"
echo ""

echo "🚀 测试步骤："
echo "1. 重启bookingservice"
echo "2. 登录教练账号"
echo "3. 访问 /dashboard/coach"
echo "4. 检查项目卡片"
echo "5. 检查时间表显示"
echo "6. 测试周切换功能"
echo ""

echo "💡 注意事项："
echo "- 确保有已确认的session和availability预约"
echo "- 检查API路径是否正确"
echo "- 验证时间格式转换"
