#!/bin/bash

# 测试修复available-slots接口的SQL逻辑错误
echo "🔧 修复available-slots接口的SQL逻辑错误"
echo "====================================="

echo "📋 问题分析："
echo "原SQL查询逻辑错误："
echo "1. 使用MIN/MAX合并所有占用时段"
echo "2. 错误地将多个独立时段合并成一个大时段"
echo "3. 导致10:00-14:00时段被错误排除"
echo ""

echo "🔧 问题原因："
echo "原SQL:"
echo "  merged_occupied AS ("
echo "    SELECT MIN(occupied_start) as start_time,"
echo "           MAX(occupied_end) as end_time"
echo "    FROM occupied_slots"
echo "  )"
echo ""
echo "这个逻辑错误："
echo "- 15:00-16:00已预约 → occupied_start=14:00, occupied_end=17:00"
echo "- MIN(14:00)=14:00, MAX(17:00)=17:00"
echo "- 结果：14:00-17:00都被认为占用"
echo "- 导致10:00-14:00被错误排除"
echo ""

echo "🔧 修复方案："
echo "1. ✅ 移除错误的CTE查询"
echo "2. ✅ 直接调用PostgreSQL函数"
echo "3. ✅ 使用已修复的get_availability_available_slots函数"
echo ""

echo "📊 修复详情："
echo "原查询："
echo "  WITH availability_range AS (...),"
echo "       occupied_slots AS (...),"
echo "       merged_occupied AS (SELECT MIN/MAX ...)"
echo "  SELECT ... FROM availability_range LEFT JOIN merged_occupied"
echo ""
echo "修复后："
echo "  SELECT slot_start, slot_end, duration_minutes"
echo "  FROM public.get_availability_available_slots(#{availabilityId})"
echo "  ORDER BY slot_start ASC"
echo ""

echo "🎯 预期结果："
echo "- 10:00-18:00 availability，15:00-16:00已预约"
echo "- 返回：10:00-14:00 和 17:00-18:00"
echo "- 正确处理1小时缓冲：14:00-17:00为占用时段"
echo ""

echo "🚀 测试步骤："
echo "1. 在Supabase中执行更新的SQL函数"
echo "2. 重启bookingservice"
echo "3. 测试10:00-18:00 availability"
echo "4. 预约15:00-16:00时段"
echo "5. 调用available-slots API"
echo "6. 验证返回10:00-14:00和17:00-18:00"
echo ""

echo "💡 调试信息："
echo "- 检查PostgreSQL函数是否正确处理多个时段"
echo "- 验证1小时缓冲计算"
echo "- 确认时区处理正确"
