#!/bin/bash

# 测试统一教练dashboard时间表显示格式
echo "🔧 统一教练dashboard时间表显示格式"
echo "================================"

echo "📋 需求描述："
echo "教练dashboard时间表不区分session和availability"
echo "统一显示为session格式：课程名字、时间、位置"
echo ""

echo "🔧 修改内容："
echo "1. ✅ CoachCenterPage.tsx - 统一事件格式"
echo "2. ✅ UserScheduleWeekView.tsx - 统一颜色显示"
echo "3. ✅ 优先显示课程名称"
echo "4. ✅ 统一使用绿色背景"
echo ""

echo "📊 修改详情："
echo "CoachCenterPage.tsx:"
echo "  - kind: 'session' (统一显示为session)"
echo "  - title: session.courseName || session.title (优先课程名称)"
echo "  - course: session.courseName || session.title"
echo ""
echo "UserScheduleWeekView.tsx:"
echo "  - getEventColor: 统一返回 'bg-green-500'"
echo "  - 移除availability的蓝色区分"
echo ""

echo "🎯 预期结果："
echo "Session预约："
echo "  - 显示课程名称（如：瑜伽基础课程）"
echo "  - 显示时间（如：10:00-11:00）"
echo "  - 显示位置（如：健身房A）"
echo "  - 绿色背景"
echo ""
echo "Availability预约："
echo "  - 显示课程名称（如：瑜伽基础课程）"
echo "  - 显示预约时间（如：15:00-16:00）"
echo "  - 显示位置（如：健身房A）"
echo "  - 绿色背景（与session一致）"
echo ""

echo "🚀 测试步骤："
echo "1. 重启前端开发服务器"
echo "2. 登录教练账号"
echo "3. 访问 /dashboard/coach"
echo "4. 检查时间表显示"
echo "5. 验证session和availability显示一致"
echo "6. 确认课程名称、时间、位置都正确显示"
echo ""

echo "💡 注意事项："
echo "- 确保后端API返回courseName字段"
echo "- 验证时间格式正确"
echo "- 检查位置信息显示"
