#!/bin/bash

# 测试修复available-slots接口逻辑
echo "🔧 修复available-slots接口逻辑"
echo "============================="

echo "📋 问题描述："
echo "Availability: 10:00-18:00"
echo "已预约: 15:00-16:00"
echo "预期结果: 10:00-14:00 和 17:00-18:00"
echo "实际结果: 只有 17:00-18:00"
echo ""

echo "🔧 问题原因："
echo "原函数逻辑缺陷："
echo "1. 只处理已预约时段之间的空隙"
echo "2. 没有处理第一个已预约时段之前的空隙"
echo "3. 缺少对无预约情况的处理"
echo ""

echo "🔧 修复内容："
echo "1. ✅ 添加v_has_bookings标志"
echo "2. ✅ 处理第一个已预约时段之前的空隙"
echo "3. ✅ 处理无预约时返回整个availability时段"
echo "4. ✅ 保持1小时缓冲逻辑"
echo ""

echo "📊 修复逻辑："
echo "原逻辑："
echo "  v_prev_end := v_availability_start"
echo "  FOR 已预约时段 LOOP"
echo "    IF v_occupied_start > v_prev_end THEN"
echo "      -- 添加空隙时段"
echo "    END IF"
echo "    v_prev_end := GREATEST(v_prev_end, v_occupied_end)"
echo "  END LOOP"
echo ""
echo "修复后："
echo "  v_prev_end := v_availability_start"
echo "  v_has_bookings := false"
echo "  FOR 已预约时段 LOOP"
echo "    v_has_bookings := true"
echo "    IF v_occupied_start > v_prev_end THEN"
echo "      -- 添加空隙时段（包括第一个预约前的空隙）"
echo "    END IF"
echo "    v_prev_end := GREATEST(v_prev_end, v_occupied_end)"
echo "  END LOOP"
echo "  IF NOT v_has_bookings THEN"
echo "    -- 返回整个availability时段"
echo "  ELSE"
echo "    -- 添加最后一个空隙时段"
echo "  END IF"
echo ""

echo "🎯 预期结果："
echo "- 10:00-18:00 availability，无预约 → 返回 10:00-18:00"
echo "- 10:00-18:00 availability，15:00-16:00已预约 → 返回 10:00-14:00 和 17:00-18:00"
echo "- 10:00-18:00 availability，10:00-12:00已预约 → 返回 13:00-18:00"
echo "- 10:00-18:00 availability，16:00-18:00已预约 → 返回 10:00-15:00"
echo ""

echo "🚀 测试步骤："
echo "1. 在Supabase中执行更新的SQL函数"
echo "2. 重启bookingservice"
echo "3. 测试10:00-18:00 availability"
echo "4. 预约15:00-16:00时段"
echo "5. 检查available-slots API返回结果"
echo "6. 验证是否返回10:00-14:00和17:00-18:00"
echo ""

echo "💡 注意事项："
echo "- 确保1小时缓冲逻辑正确"
echo "- 检查时间格式和时区"
echo "- 验证边界条件处理"
